# Generated by Django 5.2.4 on 2026-04-13 10:19

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(max_length=254, validators=[users.utils.validate_real_email], verbose_name='Company email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_email',
            field=models.EmailField(blank=True, max_length=254, validators=[users.utils.validate_real_email]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, validators=[users.utils.validate_real_email]),
        ),
    ]
