# Generated by Django 5.2.4 on 2026-04-13 10:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
