# Generated by Django 5.2.4 on 2026-04-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
