# Generated by Django 5.2.4 on 2026-04-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='company_logo',
        ),
    ]
