# Generated by Django 5.2.4 on 2026-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
