# Generated by Django 5.2.4 on 2026-03-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_shipment_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='error_message',
        ),
    ]
