# Generated by Django 5.2.4 on 2025-12-20 16:05

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_product_image2_product_image3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Atsiėmimas vietoje'), ('parcel', 'Pristatymas į paštomatą (+3,50€)')], max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Kortele'), ('cash', 'Grynaisiais')], max_length=20)),
                ('locker_company', models.CharField(blank=True, choices=[('dpd', 'DPD'), ('omniva', 'Omniva'), ('lp express', 'LP Express')], max_length=30, null=True)),
                ('locker', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(default='In process...', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'uzsakymas',
                'verbose_name_plural': 'uzsakymas',
                'db_table': 'uzsakymas',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'uzsakymo prekiai',
                'verbose_name_plural': 'uzsakymo prekiai',
                'db_table': 'uzsakymo prekiai',
            },
        ),
    ]
