# Generated by Django 5.2.4 on 2025-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
