# Generated by Django 5.2.4 on 2026-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipment_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
